docker isusue

diff --git a/jenkin/frontend/Jenkinsfile b/jenkin/frontend/Jenkinsfile
--- a/jenkin/frontend/Jenkinsfile
+++ b/jenkin/frontend/Jenkinsfile
@@ -1,113 +1,278 @@
 pipeline {
-    agent any 
-    tools {
-        jdk 'jdk'
-        nodejs 'nodejs'
+agent any
+
+
+parameters {
+    string(name: 'AWS_REGION', defaultValue: 'us-east-1', description: 'AWS Region')
+    string(name: 'AWS_ACCOUNT_ID', defaultValue: '347026173735', description: 'AWS Account ID')
+    string(name: 'ECR_REPO_NAME', defaultValue: 'costspike-frontend', description: 'ECR Repository Name')
+    string(name: 'VERSION', defaultValue: 'latest', description: 'Docker Image Version')
+    string(name: 'CLUSTER_NAME', defaultValue: 'costspike-cluster', description: 'EKS Cluster Name')
+}
+
+tools {
+    jdk 'jdk'
+    nodejs 'nodejs'
+}
+
+environment {
+    SCANNER_HOME = tool('sonarqube-scanner')
+    FRONTEND_DIR = 'frontend/aws-alert-frontend'
+    IMAGE_URI = "${params.AWS_ACCOUNT_ID}.dkr.ecr.${params.AWS_REGION}.amazonaws.com/${params.ECR_REPO_NAME}"
+}
+
+stages {
+
+    stage('Checkout Source Code') {
+        steps {
+            git branch: 'main',
+                url: 'https://github.com/shubhsJadhav95/AWS_COST_ALERT.git'
+        }
     }
-    environment  {
-        SCANNER_HOME=tool 'sonar-scanner'
-        AWS_ACCOUNT_ID = credentials('ACCOUNT_ID')
-        AWS_ECR_REPO_NAME = credentials('ECR_REPO1')
-        AWS_DEFAULT_REGION = 'us-east-1'
-        REPOSITORY_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/"
+
+    stage('Verify Workspace') {
+        steps {
+            sh '''
+            pwd
+            ls -la
+            find . -name package.json
+            '''
+        }
     }
-    stages {
-        stage('Cleaning Workspace') {
-            steps {
-                cleanWs()
-            }
-        }
-        stage('Checkout from Git') {
-            steps {
-                git credentialsId: 'GITHUB', url: 'https://github.com/AmanPathak-DevOps/End-to-End-Kubernetes-Three-Tier-DevSecOps-Project.git'
-            }
-        }
-        stage('Sonarqube Analysis') {
-            steps {
-                dir('Application-Code/frontend') {
-                    withSonarQubeEnv('sonar-server') {
-                        sh ''' $SCANNER_HOME/bin/sonar-scanner \
-                        -Dsonar.projectName=three-tier-frontend \
-                        -Dsonar.projectKey=three-tier-frontend '''
-                    }
-                }
-            }
-        }
-        stage('Quality Check') {
-            steps {
-                script {
-                    waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token' 
-                }
-            }
-        }
-        stage('OWASP Dependency-Check Scan') {
-            steps {
-                dir('Application-Code/frontend') {
-                    dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'DP-Check'
-                    dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
-                }
-            }
-        }
-        stage('Trivy File Scan') {
-            steps {
-                dir('Application-Code/frontend') {
-                    sh 'trivy fs . > trivyfs.txt'
-                }
-            }
-        }
-        stage("Docker Image Build") {
-            steps {
-                script {
-                    dir('Application-Code/frontend') {
-                            sh 'docker system prune -f'
-                            sh 'docker container prune -f'
-                            sh 'docker build -t ${AWS_ECR_REPO_NAME} .'
-                    }
-                }
-            }
-        }
-        stage("ECR Image Pushing") {
-            steps {
-                script {
-                        sh 'aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REPOSITORY_URI}'
-                        sh 'docker tag ${AWS_ECR_REPO_NAME} ${REPOSITORY_URI}${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}'
-                        sh 'docker push ${REPOSITORY_URI}${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}'
-                }
-            }
-        }
-        stage("TRIVY Image Scan") {
-            steps {
-                sh 'trivy image ${REPOSITORY_URI}${AWS_ECR_REPO_NAME}:${BUILD_NUMBER} > trivyimage.txt' 
-            }
-        }
-        stage('Checkout Code') {
-            steps {
-                git credentialsId: 'GITHUB', url: 'https://github.com/AmanPathak-DevOps/End-to-End-Kubernetes-Three-Tier-DevSecOps-Project.git'
-            }
-        }
-        stage('Update Deployment file') {
-            environment {
-                GIT_REPO_NAME = "End-to-End-Kubernetes-Three-Tier-DevSecOps-Project"
-                GIT_USER_NAME = "AmanPathak-DevOps"
-            }
-            steps {
-                dir('Kubernetes-Manifests-file/Frontend') {
-                    withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
-                        sh '''
-                            git config user.email "aman07pathak@gmail.com"
-                            git config user.name "AmanPathak-DevOps"
-                            BUILD_NUMBER=${BUILD_NUMBER}
-                            echo $BUILD_NUMBER
-                            imageTag=$(grep -oP '(?<=frontend:)[^ ]+' deployment.yaml)
-                            echo $imageTag
-                            sed -i "s/${AWS_ECR_REPO_NAME}:${imageTag}/${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}/" deployment.yaml
-                            git add deployment.yaml
-                            git commit -m "Update deployment Image to version \${BUILD_NUMBER}"
-                            git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:master
-                        '''
-                    }
+
+    stage('SonarQube Analysis') {
+        steps {
+            dir("${FRONTEND_DIR}") {
+                withSonarQubeEnv('sonar-server') {
+                    sh """
+                    ${SCANNER_HOME}/bin/sonar-scanner \
+                    -Dsonar.projectName=costspike-frontend \
+                    -Dsonar.projectKey=costspike-frontend
+                    """
                 }
             }
         }
     }
+
+    stage('Quality Gate') {
+        steps {
+            timeout(time: 10, unit: 'MINUTES') {
+                waitForQualityGate abortPipeline: true
+            }
+        }
+    }
+
+    stage('OWASP Dependency Check') {
+        steps {
+            dir("${FRONTEND_DIR}") {
+                dependencyCheck(
+                    additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit',
+                    odcInstallation: 'DP-Check'
+                )
+
+                dependencyCheckPublisher(
+                    pattern: '**/dependency-check-report.xml'
+                )
+            }
+        }
+    }
+
+    stage('Install Dependencies') {
+        steps {
+            dir("${FRONTEND_DIR}") {
+                sh '''
+                npm install
+                '''
+            }
+        }
+    }
+
+    stage('Trivy Filesystem Scan') {
+        steps {
+            dir("${FRONTEND_DIR}") {
+                sh '''
+                trivy fs --format table -o trivy-report.txt .
+                '''
+            }
+        }
+    }
+
+    stage('Build Docker Image') {
+        steps {
+            dir("${FRONTEND_DIR}") {
+                sh '''
+                docker build -t ${ECR_REPO_NAME}:${BUILD_NUMBER} .
+                '''
+            }
+        }
+    }
+
+    stage('Create ECR Repository') {
+        steps {
+            withCredentials([
+                string(credentialsId: 'AWS_ACCESS_KEY', variable: 'AWS_ACCESS_KEY'),
+                string(credentialsId: 'AWS_SECRET_KEY', variable: 'AWS_SECRET_KEY')
+            ]) {
+
+                sh '''
+                export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
+                export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
+
+                aws ecr describe-repositories \
+                --repository-names ${ECR_REPO_NAME} \
+                --region ${AWS_REGION} || \
+                aws ecr create-repository \
+                --repository-name ${ECR_REPO_NAME} \
+                --region ${AWS_REGION}
+                '''
+            }
+        }
+    }
+
+    stage('Login to ECR') {
+        steps {
+            withCredentials([
+                string(credentialsId: 'AWS_ACCESS_KEY', variable: 'AWS_ACCESS_KEY'),
+                string(credentialsId: 'AWS_SECRET_KEY', variable: 'AWS_SECRET_KEY')
+            ]) {
+
+                sh '''
+                export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
+                export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
+
+                aws ecr get-login-password \
+                --region ${AWS_REGION} | \
+                docker login \
+                --username AWS \
+                --password-stdin \
+                ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
+                '''
+            }
+        }
+    }
+
+    stage('Tag Docker Image') {
+        steps {
+            sh '''
+            docker tag ${ECR_REPO_NAME}:${BUILD_NUMBER} ${IMAGE_URI}:${BUILD_NUMBER}
+            docker tag ${ECR_REPO_NAME}:${BUILD_NUMBER} ${IMAGE_URI}:latest
+            '''
+        }
+    }
+
+    stage('Push Docker Image') {
+        steps {
+            sh '''
+            docker push ${IMAGE_URI}:${BUILD_NUMBER}
+            docker push ${IMAGE_URI}:latest
+            '''
+        }
+    }
+
+  stage('Configure EKS Access') {
+    steps {
+        withCredentials([
+            string(credentialsId: 'AWS_ACCESS_KEY', variable: 'AWS_ACCESS_KEY'),
+            string(credentialsId: 'AWS_SECRET_KEY', variable: 'AWS_SECRET_KEY')
+        ]) {
+            sh '''
+                set -e
+
+                export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
+                export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
+                export AWS_DEFAULT_REGION=${AWS_REGION}
+
+                aws sts get-caller-identity
+
+                aws eks update-kubeconfig \
+                    --region ${AWS_REGION} \
+                    --name ${CLUSTER_NAME}
+
+                # Save kubeconfig path for later stages
+                echo "export KUBECONFIG=/var/lib/jenkins/.kube/config" > kube.env
+            '''
+        }
+    }
+}
+
+    stage('Update Deployment Image') {
+        steps {
+            script {
+                def IMAGE_NAME = "${IMAGE_URI}:${params.VERSION}"
+
+                sh """
+                sed -i 's|image: .*|image: ${IMAGE_NAME}|' k8s/frontend/deployment.yml
+                """
+            }
+        }
+    }
+
+   stage('Deploy to EKS') {
+    steps {
+        withCredentials([
+            string(credentialsId: 'AWS_ACCESS_KEY', variable: 'AWS_ACCESS_KEY'),
+            string(credentialsId: 'AWS_SECRET_KEY', variable: 'AWS_SECRET_KEY')
+        ]) {
+            sh '''
+                set -e
+
+                export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
+                export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
+                export AWS_DEFAULT_REGION=${AWS_REGION}
+
+                export KUBECONFIG=/var/lib/jenkins/.kube/config
+                kubectl create namespace costspike
+                kubectl apply -f k8s/frontend/deployment.yml
+                kubectl apply -f k8s/frontend/service.yml
+            '''
+        }
+    }
+}
+
+    stage('Verify Deployment') {
+        steps {
+            withCredentials([
+                string(credentialsId: 'AWS_ACCESS_KEY', variable: 'AWS_ACCESS_KEY'),
+                string(credentialsId: 'AWS_SECRET_KEY', variable: 'AWS_SECRET_KEY')
+            ]) {
+                sh '''
+                    export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
+                    export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
+                    export AWS_DEFAULT_REGION=${AWS_REGION}
+    
+                    export KUBECONFIG=/var/lib/jenkins/.kube/config
+    
+                    kubectl get pods -A
+                    kubectl get svc -A
+                '''
+            }
+        }
+    }
+    stage('Cleanup Docker Images') {
+    steps {
+        sh '''
+            docker rmi ${IMAGE_URI}:${BUILD_NUMBER} || true
+            docker rmi ${IMAGE_URI}:latest || true
+            docker image prune -f
+        '''
+    }
+}
+}
+
+post {
+
+    success {
+        echo 'Pipeline completed successfully'
+    }
+
+    failure {
+        echo 'Pipeline failed'
+    }
+
+    always {
+        archiveArtifacts artifacts: '**/trivy-report.txt', allowEmptyArchive: true
+    }
+}
+
+
 }
